/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Main.user;
import db.konekdb;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Statement;

/**
 *
 * @author LenataHoma
 */
public class LoginPageNew extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    user usr = new user();

    public LoginPageNew() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void login() {
        try {
            String sql = "SELECT * FROM `tb_pengguna` WHERE username = '"+UsernamePengguna.getText()+"' && kata_sandi = '"+KataSandiPengguna.getText()+"';";
            Connection con = (Connection) konekdb.GetConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                usr.setNama(rs.getString("username"));
                usr.setHak_akses("hak_akses");
                usr.setId_pengguna("id_pengguna");
                if (rs.getString("hak_akses").equals("ADMIN")) {
                    JOptionPane.showMessageDialog(this, "Berhasil Masuk!!", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
                    Main.MainFrame mn = new Main.MainFrame();
                    mn.setVisible(true);
                    this.dispose();
                } else if(rs.getString("hak_akses").equals("KARYAWAN")){
                    JOptionPane.showMessageDialog(this, "Berhasil Masuk!!", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
                    Main.MainFrameKaryawan mn = new Main.MainFrameKaryawan();
                    mn.setVisible(true);
                    this.dispose();
                }else {
                    JOptionPane.showMessageDialog(this, ". Masuk!!", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Username Atau Katasandi Salah!!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        button2 = new Swing.Button();
        button1 = new Swing.Button();
        KataSandiPengguna = new Swing.PasswordField();
        UsernamePengguna = new Swing.TextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1153, 707));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button2.setBackground(new java.awt.Color(238, 238, 238));
        button2.setText("Lupa Kata Sandi?");
        button2.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jPanel2.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 390, 110, -1));

        button1.setBackground(new java.awt.Color(253, 144, 39));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("MASUK");
        button1.setFont(new java.awt.Font("Quicksand", 1, 15)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel2.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 100, 40));

        KataSandiPengguna.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        KataSandiPengguna.setLabelText("Kata Sandi");
        KataSandiPengguna.setLineColor(new java.awt.Color(253, 144, 39));
        KataSandiPengguna.setOpaque(false);
        KataSandiPengguna.setShowAndHide(true);
        KataSandiPengguna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KataSandiPenggunaKeyPressed(evt);
            }
        });
        jPanel2.add(KataSandiPengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 340, 320, -1));

        UsernamePengguna.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        UsernamePengguna.setLabelText("Nama Pengguna");
        UsernamePengguna.setLineColor(new java.awt.Color(253, 144, 39));
        UsernamePengguna.setOpaque(false);
        jPanel2.add(UsernamePengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 270, 320, 50));

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 100, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/loginPagenoTxtField.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 690));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        if (!(UsernamePengguna.getText().equals(""))) {
            if (!(KataSandiPengguna.getText().equals(""))) {
                login();
            } else {
                JOptionPane.showMessageDialog(null, "Password Tidak Boleh Kosong");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Username Tidak Boleh Kosong");
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void KataSandiPenggunaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KataSandiPenggunaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!(UsernamePengguna.getText().equals(""))) {
                if (!(KataSandiPengguna.getText().equals(""))) {
                    login();
                } else {
                    JOptionPane.showMessageDialog(null, "Password Tidak Boleh Kosong");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Username Tidak Boleh Kosong");
            }
        }
    }//GEN-LAST:event_KataSandiPenggunaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPageNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPageNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPageNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPageNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPageNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.PasswordField KataSandiPengguna;
    private Swing.TextField UsernamePengguna;
    private Swing.Button button1;
    private Swing.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
