/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Laporan;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import db.konekdb;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fathan
 */
public class laporan extends javax.swing.JInternalFrame {
DateFormat hari = new SimpleDateFormat("yyyy-MM-dd");
String a = hari.format(Calendar.getInstance().getTime());
    /**
     * Creates new form 
     */
    public laporan() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI gui = (BasicInternalFrameUI) this.getUI();
        gui.setNorthPane(null);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        loadDataHariIni();
        
    }
//    private void loadTable(){
//        DefaultTableModel table2 = new DefaultTableModel();
//        table2.addColumn("Tanggal Transaksi");
//        table2.addColumn("Jumlah Laba");
//        try {
//            String sql = "SELECT tb_transjual.tgl_transaksi,tb_detail_transjual.id_barang, SUM((tb_barang.harga_jual - tb_barang.harga_dasar) * tb_detail_transjual.jumlah) AS laba\n"
//                    + "FROM tb_detail_transjual\n"
//                    + "JOIN tb_transjual\n"
//                    + "ON tb_transjual.id_transjual = tb_detail_transjual.id_transjual\n"
//                    + "JOIN tb_barang\n"
//                    + "ON tb_barang.id_barang = tb_detail_transjual.id_barang\n"
//                    + "GROUP BY tb_transjual.tgl_transaksi;";
//            java.sql.Connection conn = (Connection)konekdb.GetConnection();
//            java.sql.Statement stm = conn.createStatement();
//            java.sql.ResultSet rs = stm.executeQuery(sql);
//            while (rs.next()) {                
//                table2.addRow(new Object[]{
//                    rs.getString("tgl_transaksi"),
//                    rs.getString("laba")
//                });
//                
//            jTable1.setModel(table2);
//            }
//        } catch (Exception e) {
//        }
//    }
    public void loadDataHariIni(){
        try {
            String loadPendapatandanLaba = "SELECT SUM(tb_jual.total_harga) AS Pendapatan, SUM((tb_produk.harga_jual - tb_produk.harga_beli)*tb_detailjual.jumlah_produk) AS Laba\n"
                    + "FROM tb_jual\n"
                    + "JOIN tb_detailjual\n"
                    + "ON tb_jual.id_transaksi = tb_detailjual.id_transaksi\n"
                    + "JOIN tb_produk\n"
                    + "ON tb_detailjual.id_produk = tb_produk.id_produk\n"
                    + "WHERE tb_jual.tgl_transaksi = '"+a+"'\n"
                    + "GROUP BY tb_jual.id_transaksi";
            java.sql.Connection con = (Connection)konekdb.GetConnection();
            java.sql.Statement st = con.createStatement();
            java.sql.ResultSet res = st.executeQuery(loadPendapatandanLaba);
            if (res.next()) {
                txt_PendapatanHarian.setText("Rp"+res.getString("Pendapatan"));
                txt_labaHarian.setText("Rp"+res.getString("Laba"));
            }
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }
    /**
     * 
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        button2 = new Swing.Button();
        button1 = new Swing.Button();
        panel_Harian = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        button3 = new Swing.Button();
        panel_pendapatanHarian5 = new Swing.PanelRound();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_TransaksiPembelianHarian = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        panel_pendapatanHarian4 = new Swing.PanelRound();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_TransaksiPenjualanHarian = new javax.swing.JTable();
        panel_pendapatanHarian3 = new Swing.PanelRound();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panel_pendapatanHarian2 = new Swing.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panel_pendapatanHarian1 = new Swing.PanelRound();
        jLabel9 = new javax.swing.JLabel();
        txt_labaHarian = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panel_pendapatanHarian = new Swing.PanelRound();
        jLabel6 = new javax.swing.JLabel();
        txt_PendapatanHarian = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panel_Bulanan = new javax.swing.JPanel();
        bg_harianBulanan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(960, 710));
        setPreferredSize(new java.awt.Dimension(960, 710));
        setVisible(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setBackground(new java.awt.Color(238, 238, 238));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel3.setBackground(new java.awt.Color(238, 238, 238));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button2.setBackground(new java.awt.Color(253, 144, 39));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setText("BULANAN");
        button2.setFont(new java.awt.Font("Quicksand Medium", 0, 12)); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel3.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 120, 100, 30));

        button1.setBackground(new java.awt.Color(253, 144, 39));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("HARIAN");
        button1.setFont(new java.awt.Font("Quicksand Medium", 0, 12)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel3.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 100, 30));

        panel_Harian.setBackground(new java.awt.Color(255, 255, 255));
        panel_Harian.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(253, 144, 39));
        jLabel5.setText("Pilih Tanggal");
        panel_Harian.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 100, 30));

        jLabel4.setFont(new java.awt.Font("Quicksand", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("20/06/2022");
        panel_Harian.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 210, 50));

        jLabel2.setFont(new java.awt.Font("Quicksand", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(253, 144, 39));
        jLabel2.setText("LAPORAN HARIAN");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel_Harian.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, 50));
        panel_Harian.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 120, 30));

        button3.setText("Cari");
        button3.setEffectColor(new java.awt.Color(253, 144, 39));
        button3.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        panel_Harian.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 50, 30));

        panel_pendapatanHarian5.setBackground(new java.awt.Color(255, 255, 255));
        panel_pendapatanHarian5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(253, 144, 39), new java.awt.Color(253, 144, 39), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        panel_pendapatanHarian5.setRoundBottomLeft(10);
        panel_pendapatanHarian5.setRoundBottomRight(10);
        panel_pendapatanHarian5.setRoundTopLeft(10);
        panel_pendapatanHarian5.setRoundTopRight(10);
        panel_pendapatanHarian5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_TransaksiPenjualanHarian.getTableHeader().setFont(new Font("Quicksand Medium", Font.PLAIN, 12));
        tabel_TransaksiPenjualanHarian.getTableHeader().setOpaque(false);
        tabel_TransaksiPenjualanHarian.getTableHeader().setBackground(new Color(255,144,39));
        tabel_TransaksiPenjualanHarian.getTableHeader().setForeground(new Color(255,255,255));
        tabel_TransaksiPembelianHarian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "ID Pemasok", "ID Pengguna", "Total Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_TransaksiPembelianHarian.setRowHeight(30);
        tabel_TransaksiPembelianHarian.setRowSelectionAllowed(false);
        tabel_TransaksiPembelianHarian.setSelectionBackground(new java.awt.Color(253, 144, 39));
        tabel_TransaksiPembelianHarian.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(tabel_TransaksiPembelianHarian);
        if (tabel_TransaksiPembelianHarian.getColumnModel().getColumnCount() > 0) {
            tabel_TransaksiPembelianHarian.getColumnModel().getColumn(0).setResizable(false);
            tabel_TransaksiPembelianHarian.getColumnModel().getColumn(1).setResizable(false);
            tabel_TransaksiPembelianHarian.getColumnModel().getColumn(2).setResizable(false);
            tabel_TransaksiPembelianHarian.getColumnModel().getColumn(3).setResizable(false);
        }

        panel_pendapatanHarian5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 660, 200));

        jLabel19.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel19.setText("Catatan Transaksi Pembelian");
        panel_pendapatanHarian5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 270, 30));

        panel_Harian.add(panel_pendapatanHarian5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 770, 720, 290));

        panel_pendapatanHarian4.setBackground(new java.awt.Color(255, 255, 255));
        panel_pendapatanHarian4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(253, 144, 39), new java.awt.Color(253, 144, 39), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        panel_pendapatanHarian4.setRoundBottomLeft(10);
        panel_pendapatanHarian4.setRoundBottomRight(10);
        panel_pendapatanHarian4.setRoundTopLeft(10);
        panel_pendapatanHarian4.setRoundTopRight(10);
        panel_pendapatanHarian4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel18.setText("Catatan Transaksi Penjualan");
        panel_pendapatanHarian4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 270, 30));

        tabel_TransaksiPenjualanHarian.getTableHeader().setFont(new Font("Quicksand Medium", Font.PLAIN, 12));
        tabel_TransaksiPenjualanHarian.getTableHeader().setOpaque(false);
        tabel_TransaksiPenjualanHarian.getTableHeader().setBackground(new Color(255,144,39));
        tabel_TransaksiPenjualanHarian.getTableHeader().setForeground(new Color(255,255,255));
        tabel_TransaksiPenjualanHarian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Diskon", "Total Harga", "ID Pengguna"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_TransaksiPenjualanHarian.setRowHeight(30);
        tabel_TransaksiPenjualanHarian.setRowSelectionAllowed(false);
        tabel_TransaksiPenjualanHarian.setSelectionBackground(new java.awt.Color(253, 144, 39));
        tabel_TransaksiPenjualanHarian.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(tabel_TransaksiPenjualanHarian);
        if (tabel_TransaksiPenjualanHarian.getColumnModel().getColumnCount() > 0) {
            tabel_TransaksiPenjualanHarian.getColumnModel().getColumn(0).setResizable(false);
            tabel_TransaksiPenjualanHarian.getColumnModel().getColumn(1).setResizable(false);
            tabel_TransaksiPenjualanHarian.getColumnModel().getColumn(2).setResizable(false);
            tabel_TransaksiPenjualanHarian.getColumnModel().getColumn(3).setResizable(false);
        }

        panel_pendapatanHarian4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 660, 200));

        panel_Harian.add(panel_pendapatanHarian4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 720, 290));

        panel_pendapatanHarian3.setBackground(new java.awt.Color(255, 255, 255));
        panel_pendapatanHarian3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 63, 63), new java.awt.Color(255, 63, 63), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        panel_pendapatanHarian3.setRoundBottomLeft(10);
        panel_pendapatanHarian3.setRoundBottomRight(10);
        panel_pendapatanHarian3.setRoundTopLeft(10);
        panel_pendapatanHarian3.setRoundTopRight(10);
        panel_pendapatanHarian3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Laporan/iconMoneyred.png"))); // NOI18N
        panel_pendapatanHarian3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 110));

        jLabel16.setFont(new java.awt.Font("Quicksand", 1, 24)); // NOI18N
        jLabel16.setText("Rp0");
        panel_pendapatanHarian3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 140, 30));

        jLabel17.setFont(new java.awt.Font("Quicksand", 1, 15)); // NOI18N
        jLabel17.setText("Pengeluaran");
        panel_pendapatanHarian3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 160, 30));

        panel_Harian.add(panel_pendapatanHarian3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 340, 110));

        panel_pendapatanHarian2.setBackground(new java.awt.Color(255, 255, 255));
        panel_pendapatanHarian2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(54, 255, 74), new java.awt.Color(54, 255, 74), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        panel_pendapatanHarian2.setRoundBottomLeft(10);
        panel_pendapatanHarian2.setRoundBottomRight(10);
        panel_pendapatanHarian2.setRoundTopLeft(10);
        panel_pendapatanHarian2.setRoundTopRight(10);
        panel_pendapatanHarian2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Laporan/iconMoneygreen.png"))); // NOI18N
        panel_pendapatanHarian2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 110));

        jLabel13.setFont(new java.awt.Font("Quicksand", 1, 24)); // NOI18N
        jLabel13.setText("Rp0");
        panel_pendapatanHarian2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 140, 30));

        jLabel14.setFont(new java.awt.Font("Quicksand", 1, 15)); // NOI18N
        jLabel14.setText("Pemasukan Lain-Lain");
        panel_pendapatanHarian2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 160, 30));

        panel_Harian.add(panel_pendapatanHarian2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 340, 110));

        panel_pendapatanHarian1.setBackground(new java.awt.Color(255, 255, 255));
        panel_pendapatanHarian1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(105, 68, 255), new java.awt.Color(105, 68, 255), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        panel_pendapatanHarian1.setRoundBottomLeft(10);
        panel_pendapatanHarian1.setRoundBottomRight(10);
        panel_pendapatanHarian1.setRoundTopLeft(10);
        panel_pendapatanHarian1.setRoundTopRight(10);
        panel_pendapatanHarian1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Laporan/iconMoneypurple.png"))); // NOI18N
        panel_pendapatanHarian1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 110));

        txt_labaHarian.setFont(new java.awt.Font("Quicksand", 1, 24)); // NOI18N
        txt_labaHarian.setText("Rp0");
        panel_pendapatanHarian1.add(txt_labaHarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 140, 30));

        jLabel11.setFont(new java.awt.Font("Quicksand", 1, 15)); // NOI18N
        jLabel11.setText("Laba per Hari");
        panel_pendapatanHarian1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 100, 30));

        panel_Harian.add(panel_pendapatanHarian1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 340, 110));

        panel_pendapatanHarian.setBackground(new java.awt.Color(255, 255, 255));
        panel_pendapatanHarian.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 140, 29), new java.awt.Color(255, 140, 29), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        panel_pendapatanHarian.setRoundBottomLeft(10);
        panel_pendapatanHarian.setRoundBottomRight(10);
        panel_pendapatanHarian.setRoundTopLeft(10);
        panel_pendapatanHarian.setRoundTopRight(10);
        panel_pendapatanHarian.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Laporan/iconMoney.png"))); // NOI18N
        panel_pendapatanHarian.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 110));

        txt_PendapatanHarian.setFont(new java.awt.Font("Quicksand", 1, 24)); // NOI18N
        txt_PendapatanHarian.setText("Rp0");
        panel_pendapatanHarian.add(txt_PendapatanHarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 140, 30));

        jLabel8.setFont(new java.awt.Font("Quicksand", 1, 15)); // NOI18N
        jLabel8.setText("Pendapatan");
        panel_pendapatanHarian.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 100, 30));

        panel_Harian.add(panel_pendapatanHarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 340, 110));

        jPanel3.add(panel_Harian, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 862, 1190));

        panel_Bulanan.setBackground(new java.awt.Color(255, 255, 255));
        panel_Bulanan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(panel_Bulanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 862, 560));

        bg_harianBulanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Laporan/bg_laporanHarian.png"))); // NOI18N
        jPanel3.add(bg_harianBulanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 890, 420));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 990, 960, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Laporan/Group 97.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 958, 700));
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1400, 870, 30));

        jScrollPane1.setViewportView(jPanel3);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        ImageIcon ic = new ImageIcon("src/Laporan/bg_laporanBulanan.png");
        bg_harianBulanan.setIcon(ic);
        panel_Bulanan.setVisible(true);
        panel_Harian.setVisible(false);
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        ImageIcon iic = new ImageIcon("src/Laporan/bg_laporanHarian.png");
        bg_harianBulanan.setIcon(iic);
        panel_Harian.setVisible(true);
        panel_Bulanan.setVisible(false);
    }//GEN-LAST:event_button1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_harianBulanan;
    private Swing.Button button1;
    private Swing.Button button2;
    private Swing.Button button3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panel_Bulanan;
    private javax.swing.JPanel panel_Harian;
    private Swing.PanelRound panel_pendapatanHarian;
    private Swing.PanelRound panel_pendapatanHarian1;
    private Swing.PanelRound panel_pendapatanHarian2;
    private Swing.PanelRound panel_pendapatanHarian3;
    private Swing.PanelRound panel_pendapatanHarian4;
    private Swing.PanelRound panel_pendapatanHarian5;
    private javax.swing.JTable tabel_TransaksiPembelianHarian;
    private javax.swing.JTable tabel_TransaksiPenjualanHarian;
    private javax.swing.JLabel txt_PendapatanHarian;
    private javax.swing.JLabel txt_labaHarian;
    // End of variables declaration//GEN-END:variables
}
