/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TransaksiBeli;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author LENOVO
 */
public class beli_utama extends javax.swing.JInternalFrame {

    /**
     * Creates new form beli_utama
     */
    public beli_utama() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI gui = (BasicInternalFrameUI) this.getUI();
        gui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tanggal_transaksi = new javax.swing.JTextField();
        id_trbeli = new javax.swing.JTextField();
        id_kasirr = new javax.swing.JTextField();
        kode_prodd = new javax.swing.JTextField();
        nama_prodd = new javax.swing.JTextField();
        harga_prodd = new javax.swing.JTextField();
        jmlh_prodd = new javax.swing.JTextField();
        id_pemasok = new javax.swing.JTextField();
        nama_pemasok = new javax.swing.JTextField();
        total_harga = new javax.swing.JTextField();
        total_hrg_label1 = new javax.swing.JLabel();
        total_hrg_label = new javax.swing.JLabel();
        btn_bayar1 = new javax.swing.JLabel();
        btn_bayar = new javax.swing.JLabel();
        btnPilihPemasok = new javax.swing.JLabel();
        btnhapus_keranjang = new javax.swing.JLabel();
        btntambah_keranjang = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(960, 723));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 870, 160));

        tanggal_transaksi.setEditable(false);
        tanggal_transaksi.setBackground(new java.awt.Color(196, 196, 196));
        tanggal_transaksi.setFont(new java.awt.Font("Quicksand SemiBold", 0, 15)); // NOI18N
        tanggal_transaksi.setBorder(null);
        getContentPane().add(tanggal_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 250, 30));

        id_trbeli.setEditable(false);
        id_trbeli.setBackground(new java.awt.Color(196, 196, 196));
        id_trbeli.setFont(new java.awt.Font("Quicksand SemiBold", 0, 15)); // NOI18N
        id_trbeli.setBorder(null);
        getContentPane().add(id_trbeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 280, 30));

        id_kasirr.setEditable(false);
        id_kasirr.setBackground(new java.awt.Color(196, 196, 196));
        id_kasirr.setFont(new java.awt.Font("Quicksand SemiBold", 0, 15)); // NOI18N
        id_kasirr.setBorder(null);
        getContentPane().add(id_kasirr, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 260, 30));

        kode_prodd.setEditable(false);
        kode_prodd.setBackground(new java.awt.Color(196, 196, 196));
        kode_prodd.setFont(new java.awt.Font("Quicksand SemiBold", 0, 15)); // NOI18N
        kode_prodd.setBorder(null);
        kode_prodd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_proddActionPerformed(evt);
            }
        });
        getContentPane().add(kode_prodd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 370, 30));

        nama_prodd.setEditable(false);
        nama_prodd.setBackground(new java.awt.Color(196, 196, 196));
        nama_prodd.setFont(new java.awt.Font("Quicksand SemiBold", 0, 15)); // NOI18N
        nama_prodd.setBorder(null);
        getContentPane().add(nama_prodd, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 450, 30));

        harga_prodd.setEditable(false);
        harga_prodd.setBackground(new java.awt.Color(196, 196, 196));
        harga_prodd.setFont(new java.awt.Font("Quicksand SemiBold", 0, 15)); // NOI18N
        harga_prodd.setBorder(null);
        getContentPane().add(harga_prodd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 150, 30));

        jmlh_prodd.setEditable(false);
        jmlh_prodd.setBackground(new java.awt.Color(196, 196, 196));
        jmlh_prodd.setFont(new java.awt.Font("Quicksand SemiBold", 0, 15)); // NOI18N
        jmlh_prodd.setBorder(null);
        getContentPane().add(jmlh_prodd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 110, 30));

        id_pemasok.setEditable(false);
        id_pemasok.setBackground(new java.awt.Color(196, 196, 196));
        id_pemasok.setFont(new java.awt.Font("Quicksand SemiBold", 0, 15)); // NOI18N
        id_pemasok.setBorder(null);
        getContentPane().add(id_pemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 170, 30));

        nama_pemasok.setEditable(false);
        nama_pemasok.setBackground(new java.awt.Color(196, 196, 196));
        nama_pemasok.setFont(new java.awt.Font("Quicksand SemiBold", 0, 15)); // NOI18N
        nama_pemasok.setBorder(null);
        getContentPane().add(nama_pemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, 170, 30));

        total_harga.setEditable(false);
        total_harga.setBackground(new java.awt.Color(196, 196, 196));
        total_harga.setFont(new java.awt.Font("Quicksand SemiBold", 0, 15)); // NOI18N
        total_harga.setBorder(null);
        getContentPane().add(total_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, 170, 30));

        total_hrg_label1.setFont(new java.awt.Font("Quicksand SemiBold", 0, 40)); // NOI18N
        total_hrg_label1.setText("RP");
        getContentPane().add(total_hrg_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, 60, 60));

        total_hrg_label.setFont(new java.awt.Font("Quicksand SemiBold", 0, 40)); // NOI18N
        total_hrg_label.setText("999,999");
        getContentPane().add(total_hrg_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 150, 60));

        btn_bayar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_bayar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TransaksiBeli/2.5.png"))); // NOI18N
        getContentPane().add(btn_bayar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 610, 180, 40));

        btn_bayar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_bayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TransaksiBeli/2.4.png"))); // NOI18N
        getContentPane().add(btn_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, 90, 40));

        btnPilihPemasok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPilihPemasok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TransaksiBeli/2.3.png"))); // NOI18N
        getContentPane().add(btnPilihPemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 140, 40));

        btnhapus_keranjang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnhapus_keranjang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TransaksiBeli/2.1.png"))); // NOI18N
        getContentPane().add(btnhapus_keranjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 120, 40));

        btntambah_keranjang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btntambah_keranjang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TransaksiBeli/2.0.png"))); // NOI18N
        getContentPane().add(btntambah_keranjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 230, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TransaksiBeli/form_beliUtama.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -60, 1020, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kode_proddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_proddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_proddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnPilihPemasok;
    private javax.swing.JLabel btn_bayar;
    private javax.swing.JLabel btn_bayar1;
    private javax.swing.JLabel btnhapus_keranjang;
    private javax.swing.JLabel btntambah_keranjang;
    private javax.swing.JTextField harga_prodd;
    private javax.swing.JTextField id_kasirr;
    private javax.swing.JTextField id_pemasok;
    private javax.swing.JTextField id_trbeli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jmlh_prodd;
    private javax.swing.JTextField kode_prodd;
    private javax.swing.JTextField nama_pemasok;
    private javax.swing.JTextField nama_prodd;
    private javax.swing.JTextField tanggal_transaksi;
    private javax.swing.JTextField total_harga;
    private javax.swing.JLabel total_hrg_label;
    private javax.swing.JLabel total_hrg_label1;
    // End of variables declaration//GEN-END:variables
}
