/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author LenataHoma
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        dpanee.removeAll();
        Beranda.form_Beranda home = new Beranda.form_Beranda();
        dpanee.add(home);
        home.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Lainnya = new javax.swing.JLabel();
        btn_laporan = new javax.swing.JLabel();
        btn_dataPemasok = new javax.swing.JLabel();
        btn_transJual = new javax.swing.JLabel();
        btn_TransaBeli = new javax.swing.JLabel();
        btn_dataStok = new javax.swing.JLabel();
        btn_dataProduk = new javax.swing.JLabel();
        btn_beranda = new javax.swing.JLabel();
        sidebarr = new javax.swing.JLabel();
        dpanee = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1233, 707));
        setMinimumSize(new java.awt.Dimension(1233, 707));
        setPreferredSize(new java.awt.Dimension(1233, 707));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Lainnya.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Lainnya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LainnyaMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Lainnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 240, 50));

        btn_laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_laporanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 240, 50));

        btn_dataPemasok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dataPemasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dataPemasokMouseClicked(evt);
            }
        });
        getContentPane().add(btn_dataPemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 240, 50));

        btn_transJual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_transJual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_transJualMouseClicked(evt);
            }
        });
        getContentPane().add(btn_transJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 395, 240, 50));

        btn_TransaBeli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_TransaBeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TransaBeliMouseClicked(evt);
            }
        });
        getContentPane().add(btn_TransaBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 240, 50));

        btn_dataStok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dataStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dataStokMouseClicked(evt);
            }
        });
        getContentPane().add(btn_dataStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 265, 240, 50));

        btn_dataProduk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dataProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dataProdukMouseClicked(evt);
            }
        });
        getContentPane().add(btn_dataProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 240, 50));

        btn_beranda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_beranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_berandaMouseClicked(evt);
            }
        });
        getContentPane().add(btn_beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 240, 50));

        sidebarr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sidebar/sidebar_beranda.png"))); // NOI18N
        getContentPane().add(sidebarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 710));

        javax.swing.GroupLayout dpaneeLayout = new javax.swing.GroupLayout(dpanee);
        dpanee.setLayout(dpaneeLayout);
        dpaneeLayout.setHorizontalGroup(
            dpaneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        dpaneeLayout.setVerticalGroup(
            dpaneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        getContentPane().add(dpanee, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 950, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_berandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_berandaMouseClicked
        // TODO add your handling code here:
        dpanee.removeAll();
        Beranda.form_Beranda home = new Beranda.form_Beranda();
        dpanee.add(home);
        home.setVisible(true);
        ImageIcon a = new ImageIcon("src/Sidebar/sidebar_beranda.png");
        sidebarr.setIcon(a);
        
        
    }//GEN-LAST:event_btn_berandaMouseClicked

    private void btn_dataProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataProdukMouseClicked
        ImageIcon a = new ImageIcon("src/Sidebar/sidebar_dataProduk.png");
        sidebarr.setIcon(a);
        dpanee.removeAll();
        DataProduk.form_DataProduk home = new DataProduk.form_DataProduk();
        dpanee.add(home);
        home.setVisible(true);
    }//GEN-LAST:event_btn_dataProdukMouseClicked

    private void btn_dataStokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataStokMouseClicked
        // TODO add your handling code here:
        dpanee.removeAll();
        DataStok.form_DataStok home = new DataStok.form_DataStok();
        dpanee.add(home);
        home.setVisible(true);
        ImageIcon a = new ImageIcon("src/Sidebar/sidebar_dataStok.png");
        sidebarr.setIcon(a);
    }//GEN-LAST:event_btn_dataStokMouseClicked

    private void btn_TransaBeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TransaBeliMouseClicked
        // TODO add your handling code here:
        dpanee.removeAll();
        TransaksiBeli.form_TransaksiBeli home = new TransaksiBeli.form_TransaksiBeli();
        dpanee.add(home);
        home.setVisible(true);
        ImageIcon a = new ImageIcon("src/Sidebar/sidebar_transbeli.png");
        sidebarr.setIcon(a);
    }//GEN-LAST:event_btn_TransaBeliMouseClicked

    private void btn_transJualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transJualMouseClicked
        // TODO add your handling code here:
        dpanee.removeAll();
        TransaksiJual.form_TransaksiJual home = new TransaksiJual.form_TransaksiJual();
        dpanee.add(home);
        home.setVisible(true);
        ImageIcon a = new ImageIcon("src/Sidebar/sidebar_transjual.png");
        sidebarr.setIcon(a);
    }//GEN-LAST:event_btn_transJualMouseClicked

    private void btn_dataPemasokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataPemasokMouseClicked
        // TODO add your handling code here:
        dpanee.removeAll();
        DataPemasok.form_dataPemasok home = new DataPemasok.form_dataPemasok();
        dpanee.add(home);
        home.setVisible(true);
        ImageIcon a = new ImageIcon("src/Sidebar/side_dataPemasok.png");
        sidebarr.setIcon(a);
    }//GEN-LAST:event_btn_dataPemasokMouseClicked

    private void btn_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseClicked
        // TODO add your handling code here:
        dpanee.removeAll();
        Laporan.form_Laporan home = new Laporan.form_Laporan();
        dpanee.add(home);
        home.setVisible(true);
        ImageIcon a = new ImageIcon("src/Sidebar/sidebar_laporan.png");
        sidebarr.setIcon(a);
    }//GEN-LAST:event_btn_laporanMouseClicked

    private void btn_LainnyaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LainnyaMouseClicked
        // TODO add your handling code here:
        dpanee.removeAll();
        Lainnya.form_Lainnya home = new Lainnya.form_Lainnya();
        dpanee.add(home);
        home.setVisible(true);
        ImageIcon a = new ImageIcon("src/Sidebar/sidebar_lainnya.png");
        sidebarr.setIcon(a);
    }//GEN-LAST:event_btn_LainnyaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Lainnya;
    private javax.swing.JLabel btn_TransaBeli;
    private javax.swing.JLabel btn_beranda;
    private javax.swing.JLabel btn_dataPemasok;
    private javax.swing.JLabel btn_dataProduk;
    private javax.swing.JLabel btn_dataStok;
    private javax.swing.JLabel btn_laporan;
    private javax.swing.JLabel btn_transJual;
    private javax.swing.JDesktopPane dpanee;
    private javax.swing.JLabel sidebarr;
    // End of variables declaration//GEN-END:variables
}
