/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Login.LoginPage;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author LenataHoma
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIcon();
        dpanee.removeAll();
        Beranda.form_Beranda home = new Beranda.form_Beranda();
        dpanee.add(home);
        home.setVisible(true);panel_logout.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_logout = new Swing.PanelRound();
        button2 = new Swing.Button();
        button1 = new Swing.Button();
        button3 = new Swing.Button();
        btn_Lainnya = new javax.swing.JLabel();
        btn_laporan = new javax.swing.JLabel();
        btn_dataPemasok = new javax.swing.JLabel();
        btn_transJual = new javax.swing.JLabel();
        btn_TransaBeli = new javax.swing.JLabel();
        btn_dataStok = new javax.swing.JLabel();
        btn_dataProduk = new javax.swing.JLabel();
        btn_beranda = new javax.swing.JLabel();
        sidebarr = new javax.swing.JLabel();
        dpanee = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("D'Kazieree (ADMIN)");
        setMaximumSize(new java.awt.Dimension(1233, 707));
        setMinimumSize(new java.awt.Dimension(1233, 707));
        setPreferredSize(new java.awt.Dimension(1233, 707));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_logout.setBackground(new java.awt.Color(255, 255, 255));
        panel_logout.setRoundBottomLeft(10);
        panel_logout.setRoundBottomRight(10);
        panel_logout.setRoundTopLeft(10);
        panel_logout.setRoundTopRight(10);
        panel_logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button2.setForeground(new java.awt.Color(253, 144, 39));
        button2.setText("Tutup Aplikasi");
        button2.setEffectColor(new java.awt.Color(253, 144, 39));
        button2.setFont(new java.awt.Font("Quicksand", 1, 13)); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        panel_logout.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, -1));

        button1.setForeground(new java.awt.Color(253, 144, 39));
        button1.setText("KeluarAkun");
        button1.setEffectColor(new java.awt.Color(253, 144, 39));
        button1.setFont(new java.awt.Font("Quicksand", 1, 13)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panel_logout.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, -1));

        getContentPane().add(panel_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 200, 130));

        button3.setBackground(new java.awt.Color(253, 144, 39));
        button3.setForeground(new java.awt.Color(255, 255, 255));
        button3.setText("Keluar");
        button3.setFont(new java.awt.Font("Quicksand", 0, 11)); // NOI18N
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        getContentPane().add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 50, -1));

        btn_Lainnya.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Lainnya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LainnyaMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Lainnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 240, 50));

        btn_laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_laporanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 240, 50));

        btn_dataPemasok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dataPemasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dataPemasokMouseClicked(evt);
            }
        });
        getContentPane().add(btn_dataPemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 240, 50));

        btn_transJual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_transJual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_transJualMouseClicked(evt);
            }
        });
        getContentPane().add(btn_transJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 395, 240, 50));

        btn_TransaBeli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_TransaBeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TransaBeliMouseClicked(evt);
            }
        });
        getContentPane().add(btn_TransaBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 240, 50));

        btn_dataStok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dataStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dataStokMouseClicked(evt);
            }
        });
        getContentPane().add(btn_dataStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 265, 240, 50));

        btn_dataProduk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dataProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dataProdukMouseClicked(evt);
            }
        });
        getContentPane().add(btn_dataProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 240, 50));

        btn_beranda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_beranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_berandaMouseClicked(evt);
            }
        });
        getContentPane().add(btn_beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 240, 50));

        sidebarr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sidebar/sidebar_beranda.png"))); // NOI18N
        sidebarr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidebarrMouseClicked(evt);
            }
        });
        getContentPane().add(sidebarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 710));

        javax.swing.GroupLayout dpaneeLayout = new javax.swing.GroupLayout(dpanee);
        dpanee.setLayout(dpaneeLayout);
        dpaneeLayout.setHorizontalGroup(
            dpaneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        dpaneeLayout.setVerticalGroup(
            dpaneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        getContentPane().add(dpanee, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 950, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_berandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_berandaMouseClicked
        // TODO add your handling code here:
        ImageIcon a = new ImageIcon("src/Sidebar/sidebar_beranda.png");
        sidebarr.setIcon(a);
        dpanee.removeAll();
        dpanee.repaint();
        Beranda.form_Beranda home = new Beranda.form_Beranda();
        dpanee.add(home);
        home.setVisible(true);
        panel_logout.setVisible(false);
    }//GEN-LAST:event_btn_berandaMouseClicked

    private void btn_dataProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataProdukMouseClicked
        ImageIcon a = new ImageIcon("src/Sidebar/sidebar_dataProduk.png");
        sidebarr.setIcon(a);
        dpanee.removeAll();
        dpanee.repaint();
        DataProduk.form_DataProduk home = new DataProduk.form_DataProduk();
        dpanee.add(home);
        home.setVisible(true);
        panel_logout.setVisible(false);
    }//GEN-LAST:event_btn_dataProdukMouseClicked

    private void btn_dataStokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataStokMouseClicked
        // TODO add your handling code here:
        ImageIcon a = new ImageIcon("src/Sidebar/sidebar_dataStok.png");
        sidebarr.setIcon(a);
        dpanee.removeAll();
        dpanee.repaint();
        DataStok.form_DataStok home = new DataStok.form_DataStok();
        dpanee.add(home);
        home.setVisible(true);
        panel_logout.setVisible(false);
        
    }//GEN-LAST:event_btn_dataStokMouseClicked

    private void btn_TransaBeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TransaBeliMouseClicked
         // TODO add your handling code here:
        ImageIcon a = new ImageIcon("src/Sidebar/sidebar_transbeli.png");
        sidebarr.setIcon(a);
        dpanee.removeAll();
        dpanee.repaint();
        TransaksiBeli.Transbeli home = new TransaksiBeli.Transbeli();
        dpanee.add(home);
        home.setVisible(true);
        panel_logout.setVisible(false);
    }//GEN-LAST:event_btn_TransaBeliMouseClicked

    private void btn_transJualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transJualMouseClicked
        // TODO add your handling code here:
        ImageIcon a = new ImageIcon("src/Sidebar/sidebar_transjual.png");
        sidebarr.setIcon(a);
        dpanee.removeAll();
        dpanee.repaint();
//        TransaksiJual.form_TransaksiJual home = new TransaksiJual.form_TransaksiJual();
        TransaksiJual.Transjual home = new TransaksiJual.Transjual();
        dpanee.add(home);
        home.setVisible(true);
        panel_logout.setVisible(false);
    }//GEN-LAST:event_btn_transJualMouseClicked

    private void btn_dataPemasokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataPemasokMouseClicked
        // TODO add your handling code here:
        dpanee.removeAll();
        dpanee.repaint();
        DataPemasok.form_dataPemasok home = new DataPemasok.form_dataPemasok();
        dpanee.add(home);
        home.setVisible(true);
        ImageIcon a = new ImageIcon("src/Sidebar/side_dataPemasok.png");
        sidebarr.setIcon(a);
        panel_logout.setVisible(false);
    }//GEN-LAST:event_btn_dataPemasokMouseClicked

    private void btn_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseClicked
        // TODO add your handling code here:
        dpanee.removeAll();
        dpanee.repaint();
        Laporan.laporan home = new Laporan.laporan();
        dpanee.add(home);
        home.setVisible(true);
        ImageIcon a = new ImageIcon("src/Sidebar/sidebar_laporan.png");
        sidebarr.setIcon(a);
        panel_logout.setVisible(false);
    }//GEN-LAST:event_btn_laporanMouseClicked

    private void btn_LainnyaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LainnyaMouseClicked
        // TODO add your handling code here:
        ImageIcon a = new ImageIcon("src/Sidebar/sidebar_lainnya.png");
        sidebarr.setIcon(a);
        dpanee.removeAll();
        dpanee.repaint();
        Lainnya.form_Lainnya home = new Lainnya.form_Lainnya();
        dpanee.add(home);
        home.setVisible(true);
        
        panel_logout.setVisible(false);
    }//GEN-LAST:event_btn_LainnyaMouseClicked

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login.LoginPageNew ln = new Login.LoginPageNew();
        ln.setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    private void sidebarrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebarrMouseClicked
        // TODO add your handling code here:
        panel_logout.setVisible(false);
    }//GEN-LAST:event_sidebarrMouseClicked

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        if (panel_logout.isVisible()) {
            panel_logout.setVisible(false);
        } else {
            panel_logout.setVisible(true);
        }
        
    }//GEN-LAST:event_button3ActionPerformed
    public void logOut(){
        this.dispose();
        dispose();
        this.validate();
//        dpanee.removeAll();
//        dpanee.repaint();
//        dispose();
//        Login.LoginPage l  = new Login.LoginPage();
//        this.dispose();
//        l.setVisible(true);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login.LoginPageNew().setVisible(true);
            }
        });
    }
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("llogo app.png")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Lainnya;
    private javax.swing.JLabel btn_TransaBeli;
    private javax.swing.JLabel btn_beranda;
    private javax.swing.JLabel btn_dataPemasok;
    private javax.swing.JLabel btn_dataProduk;
    private javax.swing.JLabel btn_dataStok;
    private javax.swing.JLabel btn_laporan;
    private javax.swing.JLabel btn_transJual;
    private Swing.Button button1;
    private Swing.Button button2;
    private Swing.Button button3;
    public javax.swing.JDesktopPane dpanee;
    private Swing.PanelRound panel_logout;
    private javax.swing.JLabel sidebarr;
    // End of variables declaration//GEN-END:variables
}

