package PengeluaranPemasukanKaryawan;



import Main.user;
import db.konekdb;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LenataHoma
 */
public class form_DataPemasukanAdmin extends javax.swing.JInternalFrame {
String IDPemasukan = null;
String IDPengguna = null;
user usr = new user();
    /**
     * Creates new form Beranda
     */
    public form_DataPemasukanAdmin() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI gui = (BasicInternalFrameUI)this.getUI();
        gui.setNorthPane(null);
        System.out.println(IDPemasukan);
        generateIDPemasukan();
//        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        Calendar cal = Calendar.getInstance();
//        jDateChooser1.setDate(cal.getTime());
        IDPengguna = usr.getId_pengguna();
        System.out.println("ID PENGGUNA : "+IDPengguna);
    }

    
    
    public void generateIDPemasukan(){
        DateFormat vblnth = new SimpleDateFormat("yyyyMMdd");
        String blnth = vblnth.format(Calendar.getInstance().getTime());

        DateFormat hari = new SimpleDateFormat("yyyy-MM-dd");
        String a = hari.format(Calendar.getInstance().getTime());
        try {
            String sql = "SELECT MAX(RIGHT(id_pemasukan,6)) AS kode_unik\n"
                    + "FROM tb_pemasukan WHERE tgl_pemasukan LIKE '" + a + "';";
            java.sql.Connection con = (Connection) konekdb.GetConnection();
            java.sql.Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            java.sql.ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                if (rs.last()) {
                    int autoId = rs.getInt(1) + 1;
                    String no = String.valueOf(autoId);
                    int noLong = no.length();
                    for (int i = 0; i < 6 - noLong; i++) {
                        no = "0" + no;
                    }
                    IDPemasukan = "IN/" + blnth + "/" + no;
                    System.out.println("ID PEMASUKAN : IN/" + blnth + "/" + no);
                }

            }
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_pendapatanHarian = new Swing.PanelRound();
        jLabel6 = new javax.swing.JLabel();
        txt_PendapatanHarian = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tb_produk = new javax.swing.JScrollPane();
        TabelProduk = new javax.swing.JTable(){

            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false; //Disallow the editing of any cell
            }

        };
        button1 = new Swing.Button();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(185, 185, 185));
        setBorder(null);
        setMaximumSize(new java.awt.Dimension(960, 710));
        setMinimumSize(new java.awt.Dimension(960, 710));
        setOpaque(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(185, 185, 185));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_pendapatanHarian.setBackground(new java.awt.Color(255, 255, 255));
        panel_pendapatanHarian.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 140, 29), new java.awt.Color(255, 140, 29), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        panel_pendapatanHarian.setRoundBottomLeft(10);
        panel_pendapatanHarian.setRoundBottomRight(10);
        panel_pendapatanHarian.setRoundTopLeft(10);
        panel_pendapatanHarian.setRoundTopRight(10);
        panel_pendapatanHarian.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Laporan/iconMoney.png"))); // NOI18N
        panel_pendapatanHarian.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 110));

        txt_PendapatanHarian.setFont(new java.awt.Font("Quicksand", 1, 24)); // NOI18N
        txt_PendapatanHarian.setText("Rp0");
        panel_pendapatanHarian.add(txt_PendapatanHarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 140, 30));

        jLabel8.setFont(new java.awt.Font("Quicksand", 1, 15)); // NOI18N
        jLabel8.setText("Pendapatan");
        panel_pendapatanHarian.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 100, 30));

        jPanel1.add(panel_pendapatanHarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 340, 110));

        tb_produk.setBorder(null);

        TabelProduk.setFont(new java.awt.Font("Quicksand Medium", 0, 15)); // NOI18N
        TabelProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Satuan", "Harga Beli", "Harga Jual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelProduk.setRowHeight(40);
        TabelProduk.getTableHeader().setResizingAllowed(false);
        TabelProduk.getTableHeader().setReorderingAllowed(false);
        TabelProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelProdukMouseClicked(evt);
            }
        });
        tb_produk.setViewportView(TabelProduk);

        jPanel1.add(tb_produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 860, 310));

        button1.setBackground(new java.awt.Color(238, 238, 238));
        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PengeluaranPemasukanKaryawan/ic_round-arrow-back.png"))); // NOI18N
        button1.setEffectColor(new java.awt.Color(247, 125, 6));
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 31, 50, 50));

        jLabel2.setFont(new java.awt.Font("Quicksand SemiBold", 0, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 125, 6));
        jLabel2.setText("Data Pemasukan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 18, 450, 75));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PengeluaranPemasukanAdmin/formPolos.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 700));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabelProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelProdukMouseClicked
        // TODO add your handling code here:
        int baris= TabelProduk.rowAtPoint(evt.getPoint());
//        kategor_jasa = TabelProduk.getValueAt(baris, 2).toString();
//        id_produk = TabelProduk.getValueAt(baris, 0).toString();
//        nama = TabelProduk.getValueAt(baris, 1).toString();
//        hargabeli = TabelProduk.getValueAt(baris, 3).toString();
//        hargajual = TabelProduk.getValueAt(baris, 4).toString();
//        System.out.println("ID PRODUK = "+id_produk);
//        System.out.println("Nama PRODUK = "+nama);
//        System.out.println("Kategori "+ kategor_jasa);
//        System.out.println("Harga Beli "+ hargabeli);
//        System.out.println("Harga Jual "+ hargajual);
        //        lbl_id.setText(id_produk);
        //        int i = TabelProduk.getSelectedRow();
        //        TableModel tm = TabelProduk.getModel();
        //        DataProdukJasa.formUbahJasa mn = new DataProdukJasa.formUbahJasa(this, true);
        //        id_produk= tm.getValueAt(i, 0).toString();
        //        mn.txt_kodeProdukJasa.setText(id_produk);
    }//GEN-LAST:event_TabelProdukMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TabelProduk;
    private Swing.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private Swing.PanelRound panel_pendapatanHarian;
    private javax.swing.JScrollPane tb_produk;
    private javax.swing.JLabel txt_PendapatanHarian;
    // End of variables declaration//GEN-END:variables
}
