package Lainnya;



import PengeluaranPemasukanAdmin.form_tambahPemasukanAdmin;
import PengeluaranPemasukanAdmin.form_tambahPengeluaranAdmin;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LenataHoma
 */
public class form_Lainnya extends javax.swing.JInternalFrame {
Main.MainFrame n = new Main.MainFrame();

    /**
     * Creates new form Beranda
     */
    public form_Lainnya() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI gui = (BasicInternalFrameUI)this.getUI();
        gui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button5 = new Swing.Button();
        button4 = new Swing.Button();
        button3 = new Swing.Button();
        button1 = new Swing.Button();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(960, 710));
        setMinimumSize(new java.awt.Dimension(960, 710));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button5.setBackground(new java.awt.Color(245, 245, 245));
        button5.setForeground(new java.awt.Color(253, 144, 39));
        button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lainnya/fluent_money-20-regular.png"))); // NOI18N
        button5.setText("   Pengeluaran");
        button5.setEffectColor(new java.awt.Color(253, 144, 39));
        button5.setFont(new java.awt.Font("Quicksand SemiBold", 0, 28)); // NOI18N
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        getContentPane().add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 390, 110));

        button4.setBackground(new java.awt.Color(245, 245, 245));
        button4.setForeground(new java.awt.Color(253, 144, 39));
        button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lainnya/fluent_money-20-regular.png"))); // NOI18N
        button4.setText("    Pemasukan");
        button4.setEffectColor(new java.awt.Color(253, 144, 39));
        button4.setFont(new java.awt.Font("Quicksand SemiBold", 0, 28)); // NOI18N
        button4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        button4.setIconTextGap(6);
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        getContentPane().add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 390, 110));

        button3.setBackground(new java.awt.Color(245, 245, 245));
        button3.setForeground(new java.awt.Color(253, 144, 39));
        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lainnya/codicon_account.png"))); // NOI18N
        button3.setText("  Pengaturan Akun");
        button3.setEffectColor(new java.awt.Color(253, 144, 39));
        button3.setFont(new java.awt.Font("Quicksand SemiBold", 0, 28)); // NOI18N
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        getContentPane().add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 390, 110));

        button1.setBackground(new java.awt.Color(245, 245, 245));
        button1.setForeground(new java.awt.Color(253, 144, 39));
        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lainnya/bi_people-fill.png"))); // NOI18N
        button1.setText("    Data Pengguna");
        button1.setEffectColor(new java.awt.Color(253, 144, 39));
        button1.setFont(new java.awt.Font("Quicksand SemiBold", 0, 28)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 390, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lainnya/Group 95.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        this.getDesktopPane().add(new dataPengguna.formDataPenggunaa()).setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:addddddddddddddddsdsdsdsdsdaddad
        this.getDesktopPane().add(new PengaturanAkun.PengaturanAkun()).setVisible(true);
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        this.getDesktopPane().add(new form_tambahPemasukanAdmin()).setVisible(true);
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        this.getDesktopPane().add(new form_tambahPengeluaranAdmin()).setVisible(true);
    }//GEN-LAST:event_button5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.Button button1;
    private Swing.Button button3;
    private Swing.Button button4;
    private Swing.Button button5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
