package Lainnya;


import DataStok.*;
import Beranda.*;
import Login.LoginPage;
import java.awt.event.MouseEvent;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import Main.MainFrame;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LenataHoma
 */
public class form_Lainnya extends javax.swing.JInternalFrame {
Main.MainFrame n = new Main.MainFrame();

    /**
     * Creates new form Beranda
     */
    public form_Lainnya() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI gui = (BasicInternalFrameUI)this.getUI();
        gui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button2 = new Swing.Button();
        button1 = new Swing.Button();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(960, 710));
        setMinimumSize(new java.awt.Dimension(960, 710));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button2.setBackground(new java.awt.Color(245, 245, 245));
        button2.setForeground(new java.awt.Color(253, 144, 39));
        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lainnya/ic_baseline-log-out.png"))); // NOI18N
        button2.setText("    Keluar");
        button2.setFont(new java.awt.Font("Quicksand SemiBold", 0, 28)); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 390, 110));

        button1.setBackground(new java.awt.Color(245, 245, 245));
        button1.setForeground(new java.awt.Color(253, 144, 39));
        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lainnya/bi_people-fill.png"))); // NOI18N
        button1.setText("    Data Pengguna");
        button1.setFont(new java.awt.Font("Quicksand SemiBold", 0, 28)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 390, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lainnya/Group 95.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        this.getDesktopPane().add(new dataPengguna.formDataPenggunaa()).setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showConfirmDialog(this, "Yakin Ingin Keluar?", "Keluar Akun", JOptionPane.INFORMATION_MESSAGE);
            switch(jawab){
                case JOptionPane.YES_OPTION:
                    LoginPage lp = new LoginPage();
                    lp.dispatchEvent(new WindowEvent(lp, WindowEvent.WINDOW_OPENED));
                    n.dispatchEvent(new WindowEvent(n, WindowEvent.WINDOW_CLOSING));
//                    n.setVisible(false);
//                    n.logOut();
                    
                    
//                    setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    break;
                case JOptionPane.NO_OPTION:
                    break;
            
            }
    }//GEN-LAST:event_button2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.Button button1;
    private Swing.Button button2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
