/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataProduk;

import db.konekdb;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author LenataHoma
 */
public class formUbahJasa extends javax.swing.JDialog {

    int x, y;
    DataProduk.form_DataProduk vm = new DataProduk.form_DataProduk();

    /**
     * Creates new form formTambahJasa
     */

    public formUbahJasa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));  //Make the frame Transparent
        this.setLocationRelativeTo(null);
//        txt_kodeProdukJasa.setText(bn.lbl_id.getText());
//        System.out.println(bn.lbl_id.getText());
//        txt_kodeProdukJasa.setText(bn.getidProduk());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_hargaJasa = new javax.swing.JTextField();
        txt_namaJasa = new javax.swing.JTextField();
        txt_kodeProdukJasa = new javax.swing.JTextField();
        btn_batal = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_hargaJasa.setFont(new java.awt.Font("Quicksand Medium", 0, 16)); // NOI18N
        txt_hargaJasa.setBorder(null);
        txt_hargaJasa.setOpaque(false);
        getContentPane().add(txt_hargaJasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 265, 360, 40));

        txt_namaJasa.setFont(new java.awt.Font("Quicksand Medium", 0, 16)); // NOI18N
        txt_namaJasa.setBorder(null);
        txt_namaJasa.setOpaque(false);
        getContentPane().add(txt_namaJasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 360, 40));

        txt_kodeProdukJasa.setFont(new java.awt.Font("Quicksand Medium", 0, 16)); // NOI18N
        txt_kodeProdukJasa.setBorder(null);
        txt_kodeProdukJasa.setOpaque(false);
        getContentPane().add(txt_kodeProdukJasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 133, 360, 40));

        btn_batal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataProduk/btn_bstal.png"))); // NOI18N
        btn_batal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batalMouseClicked(evt);
            }
        });
        getContentPane().add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 100, 40));

        btn_simpan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataProduk/btn_simpan.png"))); // NOI18N
        btn_simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 320, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataProduk/Group 118.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 700, 450));

        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 660, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataProduk/form_tambahProdukJasa (1).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 700, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        // TODO add your handling code here:
        int ex = evt.getXOnScreen();
        int ye = evt.getYOnScreen();

        this.setLocation(ex - x, ye - y);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked
        // TODO add your handling code here:
        String kp, np, sp, ib;
        ib = txt_kodeProdukJasa.getText().toString();
        kp = txt_kodeProdukJasa.getText().toString();
        np = txt_namaJasa.getText().toString();
        sp = txt_hargaJasa.getText();
        if (kp.equals("")) {
            JOptionPane.showMessageDialog(this, "Harap isi Kode Produk Jasa");
        } else if (np.equals("")) {
            JOptionPane.showMessageDialog(this, "Nama Produk Jasa Harap diisi");
        } else if (sp.equals("")) {
            JOptionPane.showMessageDialog(this, "Harga Jasa Harap diisi");
        } else {
            try {
                String update = "UPDATE tb_produk SET id_produk = '" + kp + "', nama_produk = '" + np
                        + "', harga_jual = '" + sp
                        + "' WHERE id_produk = '" + ib + "'";
                Connection con = (Connection) konekdb.GetConnection();
                PreparedStatement pst = con.prepareStatement(update);
                pst.execute();
                JOptionPane.showMessageDialog(this, "Berhasil Tersimpan!");
                form_DataProduk.loadTableProduk();
                this.dispose();                
                form_DataProduk c = new form_DataProduk();
                new Main.MainFrame().dpanee.add(c).setVisible(true);
//                this.dispose();
                txt_kodeProdukJasa.setText("");
                txt_namaJasa.setText("");
                txt_hargaJasa.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_simpanMouseClicked

    private void btn_batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseClicked
        // TODO add your handling code here:

        vm.setIdProdukJasanull(null);
        vm.setKategorinull(null);
        vm.loadTableProduk();
        this.dispose();
        //        Mainhome mn = new Mainhome();
        //        panel_tambahProdukBarang.setVisible(false);
        //        TabelProduk.setVisible(true);
        //        jScrollPane1.setVisible(true);
        //        loadTableProduk();
        //        txt_kodeprodukTambahProdukBarang.setText("");
        //        txt_tambahnamaprodukBarang.setText("");
        //        txt_satuanTambahProdukBarang.setText("");
        //        txt_hargabeliTambahProdukBarang.setText("");
        //        txt_hargajualTambahProdukBarang.setText("");
    }//GEN-LAST:event_btn_batalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formUbahJasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formUbahJasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formUbahJasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formUbahJasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                formUbahJasa dialog = new formUbahJasa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_batal;
    private javax.swing.JLabel btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JTextField txt_hargaJasa;
    public static javax.swing.JTextField txt_kodeProdukJasa;
    public static javax.swing.JTextField txt_namaJasa;
    // End of variables declaration//GEN-END:variables
}
