/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataProduk;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author LenataHoma
 */
public class form_TambahProdukBarang extends javax.swing.JDialog {
int x, y;
form_DataProduk m = new form_DataProduk();
Connection con;
    PreparedStatement pst, pst1;
    /**
     * Creates new form formTambahProdukBarang
     */
    public form_TambahProdukBarang(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_hargaJual = new javax.swing.JTextField();
        txt_hargaBeli = new javax.swing.JTextField();
        txt_satuanProduk = new javax.swing.JTextField();
        txt_namaProduk = new javax.swing.JTextField();
        txt_kodeProduk = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JLabel();
        btn_batal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_hargaJual.setFont(new java.awt.Font("Quicksand Medium", 0, 16)); // NOI18N
        txt_hargaJual.setBorder(null);
        txt_hargaJual.setOpaque(false);
        txt_hargaJual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_hargaJualKeyTyped(evt);
            }
        });
        getContentPane().add(txt_hargaJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 370, 40));

        txt_hargaBeli.setFont(new java.awt.Font("Quicksand Medium", 0, 16)); // NOI18N
        txt_hargaBeli.setBorder(null);
        txt_hargaBeli.setOpaque(false);
        txt_hargaBeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_hargaBeliKeyTyped(evt);
            }
        });
        getContentPane().add(txt_hargaBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 335, 370, 40));

        txt_satuanProduk.setFont(new java.awt.Font("Quicksand Medium", 0, 16)); // NOI18N
        txt_satuanProduk.setBorder(null);
        txt_satuanProduk.setOpaque(false);
        getContentPane().add(txt_satuanProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 273, 120, 40));

        txt_namaProduk.setFont(new java.awt.Font("Quicksand Medium", 0, 16)); // NOI18N
        txt_namaProduk.setBorder(null);
        txt_namaProduk.setOpaque(false);
        getContentPane().add(txt_namaProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 209, 370, 40));

        txt_kodeProduk.setFont(new java.awt.Font("Quicksand Medium", 0, 16)); // NOI18N
        txt_kodeProduk.setBorder(null);
        txt_kodeProduk.setOpaque(false);
        getContentPane().add(txt_kodeProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 145, 370, 40));

        btn_simpan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataProduk/btn_simpan.png"))); // NOI18N
        btn_simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 450, 100, 40));

        btn_batal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataProduk/btn_bstal.png"))); // NOI18N
        btn_batal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batalMouseClicked(evt);
            }
        });
        getContentPane().add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 100, 40));

        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 700, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataProduk/form_tamabahProdukBarang (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked
        // TODO add your handling code here:
        
        String kp, np, sp, hb, hj;
        int b,j;
        kp = txt_kodeProduk.getText().toString();
        np = txt_namaProduk.getText().toString();
        sp = txt_satuanProduk.getText();
        hb = txt_hargaBeli.getText();
        hj = txt_hargaJual.getText();
        b = Integer.parseInt(txt_hargaBeli.getText());
        j = Integer.parseInt(txt_hargaJual.getText());
        if (b < j) {
        if (kp.equals("")) {
            JOptionPane.showMessageDialog(this, "Harap isi ID Produk/Barcode Produk!", "Ada yang Kosong", JOptionPane.INFORMATION_MESSAGE);
        } else if(np.equals("")){
            JOptionPane.showMessageDialog(this, "Harap isi Nama Produk!", "Ada yang Kosong", JOptionPane.INFORMATION_MESSAGE);
        } else if(sp.equals("")){
            JOptionPane.showMessageDialog(this, "Harap isi ID Satuan Produk!", "Ada yang Kosong", JOptionPane.INFORMATION_MESSAGE);
        } else if(hb.equals("")){
            JOptionPane.showMessageDialog(this, "Harap isi Harga Beli Produk!", "Ada yang Kosong", JOptionPane.INFORMATION_MESSAGE);
        } else if (hj.equals("")) {
            JOptionPane.showMessageDialog(this, "Harap isi Harga Jual Produk", "Ada yang Kosong", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                String addProdukBarang = "INSERT INTO tb_produk VALUES('"+kp+"','"
                +np+"','"+sp+"','"+hb+"','"+hj+"');";
                String addStokKosong = "INSERT INTO tb_stokbarang VALUES('"+kp+"', '0');";
                con = (Connection)db.konekdb.GetConnection();
                pst = con.prepareStatement(addProdukBarang);
                pst1 = con.prepareStatement(addStokKosong);
                pst.execute();
                pst1.execute();
                JOptionPane.showMessageDialog(this, "Berhasil Tersimpan!", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
                form_DataProduk.loadTableProduk();
                
                this.dispose();
                txt_kodeProduk.setText("");
                txt_namaProduk.setText("");
                txt_satuanProduk.setText("");
                txt_hargaBeli.setText("");
                txt_hargaJual.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        
        }       
     } else {
            JOptionPane.showMessageDialog(null, "Harga jual harus lebih besar dari harga beli");
    }
    }//GEN-LAST:event_btn_simpanMouseClicked

    private void btn_batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseClicked
        // TODO add your handling code here:
        m.loadTableProduk();
        this.dispose();
        
//        Mainhome mn = new Mainhome();
        //        panel_tambahProdukBarang.setVisible(false);
        //        TabelProduk.setVisible(true);
        //        jScrollPane1.setVisible(true);
        //        loadTableProduk();
        //        txt_kodeprodukTambahProdukBarang.setText("");
        //        txt_tambahnamaprodukBarang.setText("");
        //        txt_satuanTambahProdukBarang.setText("");
        //        txt_hargabeliTambahProdukBarang.setText("");
        //        txt_hargajualTambahProdukBarang.setText("");
    }//GEN-LAST:event_btn_batalMouseClicked

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        // TODO add your handling code here:
        int ex = evt.getXOnScreen();
        int ye = evt.getYOnScreen();

        this.setLocation(ex-x, ye-y);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void txt_hargaBeliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hargaBeliKeyTyped
        // TODO add your handling code here:
         char k = evt.getKeyChar();
        if (!(Character.isDigit(k) || k == KeyEvent.VK_BACK_SPACE || k == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txt_hargaBeli.getText().length()>=12){
            evt.consume();
        }
    }//GEN-LAST:event_txt_hargaBeliKeyTyped

    private void txt_hargaJualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hargaJualKeyTyped
        // TODO add your handling code here:
         char k = evt.getKeyChar();
        if (!(Character.isDigit(k) || k == KeyEvent.VK_BACK_SPACE || k == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txt_hargaJual.getText().length()>=12){
            evt.consume();
        }
    }//GEN-LAST:event_txt_hargaJualKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_TambahProdukBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_TambahProdukBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_TambahProdukBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_TambahProdukBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                form_TambahProdukBarang dialog = new form_TambahProdukBarang(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_batal;
    private javax.swing.JLabel btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_hargaBeli;
    private javax.swing.JTextField txt_hargaJual;
    private javax.swing.JTextField txt_kodeProduk;
    private javax.swing.JTextField txt_namaProduk;
    private javax.swing.JTextField txt_satuanProduk;
    // End of variables declaration//GEN-END:variables
}
